/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import static Model.Orderpage.*;
import canteenmanagementsystem.CustomerInfo;
import javax.swing.*;
import canteenmanagementsystem.ItemInfo;
import canteenmanagementsystem.Order;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ragul S
 */
public class AddItem extends javax.swing.JFrame {

    /**
     * Creates new form AddItem
     */
    public AddItem() {
        setUndecorated(true);
        initComponents();
        setBounds(1033,425,473,270);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    void clearfield(){
        Additemnametxt.setText("");
        Additempricetxt.setText("");
        Addquantitytxt.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Addquantitytxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Additempricetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Addbtn = new javax.swing.JButton();
        Additemnametxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 140));
        setPreferredSize(new java.awt.Dimension(400, 278));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Addquantitytxt.setBackground(new java.awt.Color(0, 51, 153));
        Addquantitytxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Addquantitytxt.setForeground(new java.awt.Color(255, 255, 255));
        Addquantitytxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addquantitytxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Addquantitytxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Addquantitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddquantitytxtActionPerformed(evt);
            }
        });
        getContentPane().add(Addquantitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 140, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setForeground(new java.awt.Color(0, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Newly Cooked");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("  X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 480, 50));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("What's");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("New??");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 700));

        jPanel7.setBackground(new java.awt.Color(0, 51, 153));
        jPanel7.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 480, 60));

        jPanel5.setBackground(new java.awt.Color(0, 51, 153));
        jPanel5.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 640));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Item Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 30));

        Additempricetxt.setBackground(new java.awt.Color(0, 51, 153));
        Additempricetxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Additempricetxt.setForeground(new java.awt.Color(255, 255, 255));
        Additempricetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Additempricetxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Additempricetxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Additempricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditempricetxtActionPerformed(evt);
            }
        });
        jPanel2.add(Additempricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Price");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Quantity");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 33));

        Addbtn.setBackground(new java.awt.Color(0, 51, 153));
        Addbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Addbtn.setForeground(new java.awt.Color(255, 255, 255));
        Addbtn.setText("Add");
        Addbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 170, 70, 33));

        Additemnametxt.setBackground(new java.awt.Color(0, 51, 153));
        Additemnametxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Additemnametxt.setForeground(new java.awt.Color(255, 255, 255));
        Additemnametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Additemnametxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Additemnametxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Additemnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditemnametxtActionPerformed(evt);
            }
        });
        jPanel2.add(Additemnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 350, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
        
        if( Additempricetxt.getText()==null|| Addquantitytxt.getText()==null || Additemnametxt.getText()==null)
        {
            new Panead("Add Error","Please Enter all fields","").setVisible(true);
            return;
        } 
        try
        {
            String name = Additemnametxt.getText();
            double price = Double.parseDouble(Additempricetxt.getText());
            int quantity = Integer.parseInt(Addquantitytxt.getText());
            ItemInfo in = new ItemInfo(name,price,quantity);
            ItemInfo.item_array.add(in);
      
            clearfield();
            if(CanteenInterface.opov==true)
            {
                DefaultTableModel dtm = (DefaultTableModel) Orderpage.Menutable.getModel();
                dtm.setRowCount(0);
        
                for(ItemInfo it: ItemInfo.item_array){
                    if(it.getAvailable_quantity()>0)
                        dtm.addRow(new Object[]{
                            it.getName(),it.getPrice()
                        });
                }
            
                double ta=0;
                DefaultTableModel ctm = (DefaultTableModel) Carttable.getModel();
                ctm.setRowCount(0);
        
                for(Order it: CustomerInfo.order){
                    ctm.addRow(new Object[]{
                        it.getName(),it.getQ(),it.getP()
                    });
                    ta+=it.getP();
                }
                Orderpage.Totalbox.setText(String.valueOf(ta));
            }
        }
        catch(NumberFormatException e)
        {
            new Panead("Add Error","Please Enter all fields","").setVisible(true);
        }
        
    }//GEN-LAST:event_AddbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearfield();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AdditemnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditemnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdditemnametxtActionPerformed

    private void AdditempricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditempricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdditempricetxtActionPerformed

    private void AddquantitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddquantitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddquantitytxtActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JTextField Additemnametxt;
    private javax.swing.JTextField Additempricetxt;
    private javax.swing.JTextField Addquantitytxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
