/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import canteenmanagementsystem.*;
import Model.*;
import Model.ManageItems;
import static Model.Orderpage.Menutable;
import java.awt.Color;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Selva
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public static OrderplacedInfo cur_order = new OrderplacedInfo();
    public Payment() {
        setBounds(40,100,0,0);
        setUndecorated(true);
        initComponents();
        //setBounds(100,100,0,0);
        Receiptname.setText("Receipt For \n"+Login.cur_user);
        Insertcomponents.setVisible(false);
        Payableamt.setText(String.valueOf(Orderpage.grandTotal));
        Orderno.setText(String.valueOf(OrderInfo.order_id));
        Balance.setText(String.valueOf(CustomerInfo.ub.get(Login.cur_user).getBal_amount()));
        Orderbox.setText(Orderpage.order_details);
        
        ButtonGroup b = new ButtonGroup();
        b.add(card);
        b.add(cash);
        b.add(wallet);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //add(b);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Paybtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Insertcomponents = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Balance = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Receiptname = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Orderno = new javax.swing.JTextField();
        Payableamt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Orderbox = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cash = new javax.swing.JRadioButton();
        card = new javax.swing.JRadioButton();
        wallet = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(690, 632));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setText("Amount :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        Paybtn.setBackground(new java.awt.Color(102, 0, 153));
        Paybtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Paybtn.setForeground(new java.awt.Color(255, 255, 255));
        Paybtn.setText("Pay");
        Paybtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaybtnActionPerformed(evt);
            }
        });
        getContentPane().add(Paybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 80, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 153));
        jLabel4.setText("Order Details :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 140, -1));

        Insertcomponents.setBackground(new java.awt.Color(102, 0, 153));
        Insertcomponents.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153), 3));
        Insertcomponents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Card Holder Name :");
        Insertcomponents.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 25));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Card Number :");
        Insertcomponents.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 25));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CVV :");
        Insertcomponents.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 40, 25));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Valid Thru :");
        Insertcomponents.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 25));

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 0, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Insertcomponents.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, -1));

        jTextField3.setBackground(new java.awt.Color(204, 204, 255));
        jTextField3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 0, 153));
        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        Insertcomponents.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 100, -1));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 255));
        jPasswordField1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(102, 0, 153));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        Insertcomponents.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 80, -1));

        jTextField4.setBackground(new java.awt.Color(204, 204, 255));
        jTextField4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(102, 0, 153));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        Insertcomponents.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        Insertcomponents.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Credit Card details");
        Insertcomponents.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 210, 20));

        getContentPane().add(Insertcomponents, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 330, 160));

        jPanel2.setBackground(new java.awt.Color(102, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Payment");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 70));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Interface");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 260, 70));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Wallet balance :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, -1));

        Balance.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Balance.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 30, 90, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 700));

        jPanel3.setBackground(new java.awt.Color(102, 0, 153));
        jPanel3.setForeground(new java.awt.Color(0, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 160, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("  X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 30, 30));

        Receiptname.setBackground(new java.awt.Color(255, 255, 255));
        Receiptname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Receiptname.setForeground(new java.awt.Color(255, 255, 255));
        Receiptname.setText("Receipt For");
        Receiptname.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                ReceiptnameComponentHidden(evt);
            }
        });
        jPanel3.add(Receiptname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 218, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -20, 480, 50));

        jPanel5.setBackground(new java.awt.Color(102, 0, 153));
        jPanel5.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 40, 640));

        jPanel7.setBackground(new java.awt.Color(102, 0, 153));
        jPanel7.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 560, 100));

        Orderno.setBackground(new java.awt.Color(102, 0, 153));
        Orderno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Orderno.setForeground(new java.awt.Color(255, 255, 255));
        Orderno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Orderno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 120, 30));

        Payableamt.setBackground(new java.awt.Color(102, 0, 153));
        Payableamt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Payableamt.setForeground(new java.awt.Color(255, 255, 255));
        Payableamt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Payableamt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Payableamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayableamtActionPerformed(evt);
            }
        });
        getContentPane().add(Payableamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 120, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 153));
        jLabel5.setText("Order no :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setText("Choose a payment mode");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 240, 40));

        Orderbox.setEditable(false);
        Orderbox.setBackground(new java.awt.Color(102, 0, 153));
        Orderbox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Orderbox.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Orderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 140, 110));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cash.setBackground(new java.awt.Color(204, 204, 255));
        cash.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cash.setForeground(new java.awt.Color(102, 0, 153));
        cash.setText("Cash");
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });
        jPanel1.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, 40));

        card.setBackground(new java.awt.Color(204, 204, 255));
        card.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        card.setForeground(new java.awt.Color(102, 0, 153));
        card.setText("Credit Card");
        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });
        jPanel1.add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 120, 40));

        wallet.setBackground(new java.awt.Color(204, 204, 255));
        wallet.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        wallet.setForeground(new java.awt.Color(102, 0, 153));
        wallet.setText("Wallet");
        wallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletActionPerformed(evt);
            }
        });
        jPanel1.add(wallet, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 320, 80));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 420, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        Insertcomponents.setVisible(true);
        jTextField1.setText("");
        jTextField4.setText("");
        jTextField3.setText("");
        jPasswordField1.setText("");
        //Insertcomponents.setBounds(10,10,0,0);
        Paybtn.setText("Pay");
    }//GEN-LAST:event_cardActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
        Insertcomponents.setVisible(false);
        Paybtn.setText("Proceed");
    }//GEN-LAST:event_cashActionPerformed

    private void walletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletActionPerformed
        // TODO add your handling code here:
        Insertcomponents.setVisible(false);
        Paybtn.setText("Pay");
    }//GEN-LAST:event_walletActionPerformed

    private void PaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaybtnActionPerformed
        // TODO add your handling code here:
        
        
        if(!cash.isSelected() && !card.isSelected() && !wallet.isSelected()){
            /*final JOptionPane pane = new JOptionPane("Select an payment mode");
                final JDialog d = pane.createDialog((JFrame)null, "Payment");
                d.setLocation(250,350);
                d.setVisible(true);*/
            new Panecus("Payment","Select a payment mode","").setVisible(true);
        }
        
        CustomerInfo cur = CustomerInfo.ub.get(Login.cur_user);
        int flag = 0;
        
        
        
        if(cash.isSelected()){
            /*final JOptionPane pane = new JOptionPane("Ordered Placed");
                final JDialog d = pane.createDialog((JFrame)null, "Payment");
                d.setLocation(250,350);
                d.setVisible(true);*/
                new Panecus("Payment","Ordered Placed","Payment").setVisible(true);
                cur_order = new OrderplacedInfo(cur.getUsername(),"Unpaid",Orderpage.order_details,OrderInfo.order_id,Orderpage.grandTotal);
                OrderInfo.add_order(cur_order); 
                
                Orderpage.grandTotal=0;
                Orderpage.Totalbox.setText("0");
                //Orderpage.Userbal.setText(String.valueOf(bal));
        }
        else if(card.isSelected()){
            /*final JOptionPane pane = new JOptionPane("Order Placed");
                final JDialog d = pane.createDialog((JFrame)null, "Payment");
                d.setLocation(250,350);
                d.setVisible(true);
                */
                //setVisible(false);
                new Panecus("Payment","Ordered Placed","Payment").setVisible(true);
                cur_order = new OrderplacedInfo(cur.getUsername(),"paid",Orderpage.order_details,OrderInfo.order_id,Orderpage.grandTotal);
                OrderInfo.add_order(cur_order);
                Orderpage.grandTotal=0;
                Orderpage.Totalbox.setText("0");
                //Orderpage.Userbal.setText(String.valueOf(bal));
        }
        else if(wallet.isSelected()){
            
            String res ="";
            double bal = CustomerInfo.ub.get(Login.cur_user).getBal_amount();
            if(bal < Orderpage.grandTotal){
                res += "Insufficient Wallet points";
                
                /*final JOptionPane pane = new JOptionPane(res);
                final JDialog d = pane.createDialog((JFrame)null, "Payment");
                d.setLocation(250,350);
                d.setVisible(true);*/
                //setVisible(false);
                new Panecus("Payment",res,"").setVisible(true);
                flag = 1;
            }
            else{
                CustomerInfo.ub.get(Login.cur_user).detectAmount(Orderpage.grandTotal);
                bal = CustomerInfo.ub.get(Login.cur_user).getBal_amount();
                
                res += "Order placed \n Balance points : "+bal;
                
                /*final JOptionPane pane = new JOptionPane(res);
                final JDialog d = pane.createDialog((JFrame)null, "Payment");
                d.setLocation(250,350);
                d.setVisible(true);
                */
                
                new Panecus("Payment",res,"Payment").setVisible(true);
                cur_order = new OrderplacedInfo(cur.getUsername(),"paid",Orderpage.order_details,OrderInfo.order_id,Orderpage.grandTotal);
                OrderInfo.add_order(cur_order);
                Orderpage.grandTotal=0;
                Orderpage.Totalbox.setText("0");
                Orderpage.Userbal.setText(String.valueOf(bal));
                
            }
            
        }
        if(CanteenInterface.apov==true)
        {
        DefaultTableModel dtm = (DefaultTableModel) ManageItems.OrderPlacedTable.getModel();
        if(flag == 0){
            dtm.addRow(new Object[]{
                cur_order.getOrderid(),cur_order.getName(),cur_order.getTotal(),cur_order.getPayment_status()
            });
        }
        }
            
            Orderbox.setText("");
            Orderpage.order_details="";
            
            //setVisible(false);
            DefaultTableModel ctm = (DefaultTableModel) Orderpage.Carttable.getModel();
            ctm.setRowCount(0);
            DefaultTableModel dtm = (DefaultTableModel) Menutable.getModel();
        dtm.setRowCount(0);
        
        for(ItemInfo it: ItemInfo.item_array){
            if(it.getAvailable_quantity()>0)
            dtm.addRow(new Object[]{
                it.getName(),it.getPrice()
            });
        }
    }//GEN-LAST:event_PaybtnActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void PayableamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayableamtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayableamtActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Insertcomponents.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void ReceiptnameComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ReceiptnameComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceiptnameComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balance;
    private javax.swing.JPanel Insertcomponents;
    public static javax.swing.JTextField Orderbox;
    private javax.swing.JTextField Orderno;
    private javax.swing.JTextField Payableamt;
    private javax.swing.JButton Paybtn;
    private javax.swing.JLabel Receiptname;
    private javax.swing.JRadioButton card;
    private javax.swing.JRadioButton cash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton wallet;
    // End of variables declaration//GEN-END:variables
}
