/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import static Model.Login.op;
import static Model.Orderpage.Carttable;
import static Model.Orderpage.un;
import canteenmanagementsystem.CustomerInfo;
import canteenmanagementsystem.ItemInfo;
import canteenmanagementsystem.Order;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Ragul S
 */
public class SearchItems extends javax.swing.JFrame {

    /**
     * Creates new form UpdateItems
     */
    public SearchItems() {
        setUndecorated(true);
        initComponents();
        setBounds(1033,425,473,270);
        DefaultTableModel dtm = (DefaultTableModel) Edittable.getModel();
        dtm.setRowCount(0);
        
        for(ItemInfo it: ItemInfo.item_array){
            dtm.addRow(new Object[]{
                it.getName(),it.getPrice(),it.getAvailable_quantity()
            });
        }
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        /*DefaultTableModel dtm = (DefaultTableModel) Edittable.getModel();
        dtm.setRowCount(0);
        
        for(ItemInfo it: ItemInfo.item_array){
                dtm.addRow(new Object[]{
                it.getName(),it.getPrice(),it.getAvailable_quantity()
            });
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Edittable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Searchitemtxt = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(710, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Edittable.setBackground(new java.awt.Color(204, 255, 255));
        Edittable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Edittable.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Edittable.setForeground(new java.awt.Color(0, 51, 153));
        Edittable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Price", "Quanity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Edittable.setRowHeight(25);
        Edittable.setSelectionBackground(new java.awt.Color(0, 51, 153));
        Edittable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Edittable.setShowGrid(true);
        Edittable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdittableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Edittable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 270, 210));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setForeground(new java.awt.Color(0, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Update");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("  X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 480, 70));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setText("Clear");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, -1));

        Searchitemtxt.setBackground(new java.awt.Color(204, 255, 255));
        Searchitemtxt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Searchitemtxt.setForeground(new java.awt.Color(255, 132, 39));
        Searchitemtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Searchitemtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Searchitemtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, 30));

        SearchBtn.setBackground(new java.awt.Color(204, 255, 255));
        SearchBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SearchBtn.setForeground(new java.awt.Color(0, 51, 153));
        SearchBtn.setText("Search");
        SearchBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Item Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 230));

        jPanel5.setBackground(new java.awt.Color(0, 51, 153));
        jPanel5.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 640));

        jPanel7.setBackground(new java.awt.Color(0, 51, 153));
        jPanel7.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 480, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        String name = Searchitemtxt.getText();
        int flag = 0;
        //JOptionPane.showMessageDialog(null,name+" Not Found !"+ItemInfo.item_array.size());
        DefaultTableModel dtm = (DefaultTableModel) Edittable.getModel();
        dtm.setRowCount(0);
        
        for(ItemInfo it: ItemInfo.item_array){
            if(it.getName().equals(name)){
                dtm.addRow(new Object[]{
                it.getName(),it.getPrice(),it.getAvailable_quantity()
            });
                flag = 1;
            }
        }
        
        if(flag == 0){
            
            /*for(ItemInfo it: ItemInfo.item_array){
                    dtm.addRow(new Object[]{
                    it.getName(),it.getPrice(),it.getAvailable_quantity()
                });
            }*/
            new Panead("Item Error",name+" not Found","").setVisible(true);
            //JOptionPane.showMessageDialog(null,name+" Not Found !");
            Searchitemtxt.setText("");
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void EdittableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdittableMouseClicked
        
        new EditPane().setVisible(true);
        /*int index = Edittable.getSelectedRow();
        TableModel model = Edittable.getModel();
        String name = model.getValueAt(index, 0).toString();
        String price = model.getValueAt(index, 1).toString();
        String quantity = model.getValueAt(index, 2).toString();

        int flag=0;
        String[] options = { "Edit", "Delete", "Cancel" };
        int x = JOptionPane.showOptionDialog(null, "Edit or Delete?", "Select an option",  
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, null);*/
        /*int a = JOptionPane.showConfirmDialog(null, "Do you want to edit " + name+" ","Select",JOptionPane.YES_NO_CANCEL_OPTION);
        if(a == 0){
            new UpdateDetails(ItemInfo.item_array,name,price,quantity).setVisible(true);
            flag = 1;
        }

        else
            JOptionPane.showMessageDialog(null,name+" Not Found !"+ItemInfo.item_array.size());*/
       /* if(x==0)
        {
            new UpdateDetails(ItemInfo.item_array,name,price,quantity).setVisible(true);
            flag = 1;
            Searchitemtxt.setText("");
        }
        
        else if(x==1)
        {
            //ItemInfo i = new ItemInfo(name,Double.parseDouble(price),quantity);
            int a = JOptionPane.showConfirmDialog(null, "Do you want to delete " + name+" ?","Delete",JOptionPane.YES_NO_CANCEL_OPTION);
            if(a == 0){
            
                for(int i=0;i<ItemInfo.item_array.size();i++)
                {
                    if(ItemInfo.item_array.get(i).getName().equals(name))
                        ItemInfo.item_array.remove(i);
                }
                
                for(int i=0;i<CustomerInfo.order.size();i++)
                {
                    if(CustomerInfo.order.get(i).getName().equals(name))
                        CustomerInfo.order.remove(i);
                }
                
                DefaultTableModel etm = (DefaultTableModel) Edittable.getModel();
                etm.setRowCount(0);
        
                if(CanteenInterface.opov==true)
                {
                    DefaultTableModel dtm = (DefaultTableModel) Orderpage.Menutable.getModel();
                    dtm.setRowCount(0);
        
                    for(ItemInfo it: ItemInfo.item_array){
                        dtm.addRow(new Object[]{
                            it.getName(),it.getPrice()
                        });
                    }
                    double ta=0;
                    DefaultTableModel ctm = (DefaultTableModel) Carttable.getModel();
                    ctm.setRowCount(0);
        
                    for(Order it: CustomerInfo.order){
                        ctm.addRow(new Object[]{
                            it.getName(),it.getQ(),it.getP()
                        });
                        ta+=it.getP();
                    }
                    Orderpage.Totalbox.setText(String.valueOf(ta));
                }
                /*op.setVisible(false);
                Login.op = new Orderpage(un);
                op.setVisible(true);*/
                /*for(ItemInfo it: ItemInfo.item_array){
                    dtm.addRow(new Object[]{
                        it.getName(),it.getPrice(),it.getAvailable_quantity()
                    });
                }
                Searchitemtxt.setText("");*/
                
           /* }
        }
        
        if(flag==1)
        setVisible(false);*/
    }//GEN-LAST:event_EdittableMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Searchitemtxt.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Edittable;
    private javax.swing.JButton SearchBtn;
    public static javax.swing.JTextField Searchitemtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
